package com.example.testwirelesssynchronizationofmultipledistributedcameras

import android.Manifest
import android.app.Activity
import android.content.ContentValues
import android.content.Context
import android.content.pm.PackageManager
import android.content.res.Configuration
import android.graphics.*
import android.graphics.Matrix.ScaleToFit
import android.hardware.camera2.*
import android.os.Build
import android.os.Handler
import android.os.HandlerThread
import android.util.Log
import android.util.Range
import android.util.Size
import android.util.SparseIntArray
import android.view.Surface
import android.view.TextureView
import android.widget.Toast
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import java.util.*
import java.util.Collections.singletonList
import kotlin.Comparator
import android.media.MediaRecorder
import android.os.Environment
import android.os.SystemClock
import android.provider.MediaStore
import com.example.testwirelesssynchronizationofmultipledistributedcameras.DataClass.TimeSyncManager
import java.io.File
import java.util.Arrays


class Camera2(private val activity: Activity, private val textureView: AutoFitTextureView , private var role: String = "Master") {

    private var onBitmapReady: (Bitmap) -> Unit = {}
    private val cameraManager: CameraManager =
        textureView.context.getSystemService(Context.CAMERA_SERVICE) as CameraManager
    private var cameraFacing = CameraCharacteristics.LENS_FACING_BACK
    private var previewSize: Size? = null

    //Current Camera id
    private var cameraId = "-1"
    private var backgroundHandler: Handler? = null
    private var backgroundThread: HandlerThread? = null
    private var cameraDevice: CameraDevice? = null

    //
    public var cameraCaptureSession: CameraCaptureSession? = null
    private var cameraReadyCallback: CameraReadyCallback? = null

    // capture request builder for camera.
    private var captureRequestBuilder: CaptureRequest.Builder? = null

    // capture request generated by above builder.
    private var captureRequest: CaptureRequest? = null
    private var flash = FLASH.OFF
    private var cameraState = STATE_PREVIEW

    private var exposureCompensationRange: Range<Long>? = null
    private var isoRange: Range<Int>? = null
    private var focusRange: Range<Float>? = null
    private var mediaRecorder: MediaRecorder? = null
    private var isRecordingVideo: Boolean = false

    private var currentExposureTime: Long? = null
    private var currentIso: Int? = null
    private var currentFocus: Float? = null

    private var surface: Surface? = null
    private var sensorArraySize: Rect? = null
    private var maxDigitalZoom: Float = 1f
    private var currentZoom: Float = 1f  // مقدار پیش‌فرض 1 یعنی بدون زوم

    private val videoTimestamps = mutableListOf<Long>() // لیست برای ذخیره timestampها
    private var timestampFilePath: String? = null // مسیر فایل ذخیره timestampها

    /**
     * Whether the current camera device supports Flash or not.
     */
    private var isFlashSupported = true

    /**
     * Orientation of the camera sensor
     */
    private var mSensorOrientation = 0

    private var bootTimeMillis: Long = 0L


    private val cameraCaptureCallBack = object : CameraCaptureSession.CaptureCallback() {

        private fun process(captureResult: CaptureResult) {
            when (cameraState) {
// We have nothing to do when the camera preview is working normally.
                STATE_PREVIEW -> {

                }

                STATE_WAITING_LOCK -> {
                    val afState = captureResult[CaptureResult.CONTROL_AF_STATE]

                    if (afState == null) {
                        captureStillPicture()
                    } else if (afState == CaptureResult.CONTROL_AF_STATE_FOCUSED_LOCKED || afState == CaptureResult.CONTROL_AF_STATE_NOT_FOCUSED_LOCKED) {
// CONTROL_AE_STATE can be null on some devices
                        val aeState = captureResult[CaptureResult.CONTROL_AE_STATE]
                        if (aeState == null || aeState == CaptureResult.CONTROL_AE_STATE_CONVERGED) {
                            cameraState = STATE_PICTURE_TAKEN
                            captureStillPicture()

                        } else runPrecaptureSequence()
                    }
                }

                STATE_WAITING_PRECAPTURE -> {
// CONTROL_AE_STATE can be null on some devices
                    val aeState = captureResult[CaptureResult.CONTROL_AE_STATE]
                    if (aeState == null || aeState == CaptureResult.CONTROL_AE_STATE_PRECAPTURE || aeState == CaptureResult.CONTROL_AE_STATE_FLASH_REQUIRED) {
                        cameraState = STATE_WAITING_NON_PRECAPTURE
                    }


                }

                STATE_WAITING_NON_PRECAPTURE -> {
// CONTROL_AE_STATE can be null on some devices
                    val aeState = captureResult[CaptureResult.CONTROL_AE_STATE]
                    if (aeState == null || aeState != CaptureResult.CONTROL_AE_STATE_PRECAPTURE) {
                        cameraState = STATE_PICTURE_TAKEN
                        captureStillPicture()
                    }
                }
            }
        }

        override fun onCaptureProgressed(
            session: CameraCaptureSession,
            request: CaptureRequest,
            partialResult: CaptureResult
        ) {
            process(partialResult)
        }

        override fun onCaptureCompleted(
            session: CameraCaptureSession,
            request: CaptureRequest,
            result: TotalCaptureResult
        ) {
            process(result)
        }
    }


    internal companion object {
// These values represent Camera states.

        // Showing Camera Preview.
        private const val STATE_PREVIEW = 0

        // Waiting for the focus to be locked.
        private const val STATE_WAITING_LOCK = 1

        // Waiting for the exposure to be in pre-capture state.
        private const val STATE_WAITING_PRECAPTURE = 2

        // Waiting for the exposure to be in any other state except pre-capture state.
        private const val STATE_WAITING_NON_PRECAPTURE = 3

        // Picture was taken
        private const val STATE_PICTURE_TAKEN = 4

        internal const val REQUEST_CAMERA_PERMISSION = 1001

        private val ORIENTATIONS = SparseIntArray()

        init {
            ORIENTATIONS.append(Surface.ROTATION_0, 90)
            ORIENTATIONS.append(Surface.ROTATION_90, 0)
            ORIENTATIONS.append(Surface.ROTATION_180, 270)
            ORIENTATIONS.append(Surface.ROTATION_270, 180)
        }

        /**
         * Max preview width that is guaranteed by Camera2 API
         */
        private const val MAX_PREVIEW_WIDTH = 1920

        /**
         * Max preview height that is guaranteed by Camera2 API
         */
        private const val MAX_PREVIEW_HEIGHT = 1080


        // Flag to check if camera capture sessions is closed.

        //  private var cameraSessionClosed = false


        /**
         * Given {@code choices} of {@code Size}s supported by a camera, choose the smallest one that
         * is at least as large as the respective texture view size, and that is at most as large as the
         * respective max size, and whose aspect ratio matches with the specified value. If such size
         * doesn't exist, choose the largest one that is at most as large as the respective max size,
         * and whose aspect ratio matches with the specified value.
         *
         * @param choices           The list of sizes that the camera supports for the intended output
         *                          class
         * @param textureViewWidth  The width of the texture view relative to sensor coordinate
         * @param textureViewHeight The height of the texture view relative to sensor coordinate
         * @param maxWidth          The maximum width that can be chosen
         * @param maxHeight         The maximum height that can be chosen
         * @param aspectRatio       The aspect ratio
         * @return The optimal {@code Size}, or an arbitrary one if none were big enough
         */
        private fun chooseOptimalSize(
            choices: Array<Size>, textureViewWidth: Int,
            textureViewHeight: Int, maxWidth: Int, maxHeight: Int, aspectRatio: Size
        ): Size {

            // Collect the supported resolutions that are at least as big as the preview Surface
            val bigEnough = arrayListOf<Size>()
            // Collect the supported resolutions that are smaller than the preview Surface
            val notBigEnough = arrayListOf<Size>()
            val w = aspectRatio.width
            val h = aspectRatio.height
            for (option in choices) {
                if (option.width <= maxWidth && option.height <= maxHeight &&
                    option.height == option.width * h / w
                ) {
                    if (option.width >= textureViewWidth && option.height >= textureViewHeight) {
                        bigEnough.add(option)
                    } else {
                        notBigEnough.add(option)
                    }
                }
            }

            // Pick the smallest of those big enough. If there is no one big enough, pick the
            // largest of those not big enough.

            return when {
                bigEnough.isNotEmpty() -> Collections.min(bigEnough, compareSizesByArea)
                notBigEnough.isNotEmpty() -> Collections.max(notBigEnough, compareSizesByArea)
                else -> {
                    Log.e("Camera", "Couldn't find any suitable preview size")
                    choices[0]
                }
            }
        }

        private val compareSizesByArea = Comparator<Size> { lhs, rhs ->
            // We cast here to ensure the multiplications won't overflow
            java.lang.Long.signum(lhs.width.toLong() * lhs.height - rhs.width.toLong() * rhs.height)
        }

    }


//    private fun configureTransform() {
//
//    }


    private val surfaceTextureListener = object : TextureView.SurfaceTextureListener {
        override fun onSurfaceTextureSizeChanged(surface: SurfaceTexture, width: Int, height: Int) {
            //Toast.makeText(activity , "width : $width , height : $height" , Toast.LENGTH_LONG).show()
            configureTransform(width, height)
        }

        override fun onSurfaceTextureUpdated(surface: SurfaceTexture) {

        }

        override fun onSurfaceTextureDestroyed(surface: SurfaceTexture): Boolean {
            return true
        }

        override fun onSurfaceTextureAvailable(surface: SurfaceTexture, width: Int, height: Int) {
            openCamera(width, height)

        }
    }

    private val cameraStateCallback = object : CameraDevice.StateCallback() {
        override fun onOpened(camera: CameraDevice) {
            this@Camera2.cameraDevice = camera
            createPreviewSession()
        }

        override fun onDisconnected(camera: CameraDevice) {
            camera.close()
            this@Camera2.cameraDevice = null
        }

        override fun onError(camera: CameraDevice, error: Int) {
        }
    }

    fun onResume() {
        openBackgroundThread()
        if (textureView.isAvailable) {
            openCamera(textureView.width, textureView.height)
        } else textureView.surfaceTextureListener = surfaceTextureListener


    }

    fun close() {
        closeCamera()
        closeBackgroundThread()

    }


    private fun closeCamera() {
        if (cameraCaptureSession != null) {
            cameraCaptureSession!!.close()
            cameraCaptureSession = null
            //   cameraSessionClosed = true
        }

        if (cameraDevice != null) {
            cameraDevice!!.close()
            cameraDevice = null
        }
    }

    private fun closeBackgroundThread() {
        if (backgroundHandler != null) {
            backgroundThread!!.quitSafely()
            backgroundThread = null
            backgroundHandler = null
        }
    }


    internal fun openCamera(width: Int, height: Int) {
        /*        val permissions = arrayOf(
                    Manifest.permission.CAMERA,
                    Manifest.permission.RECORD_AUDIO,
                    Manifest.permission.READ_EXTERNAL_STORAGE,
                    Manifest.permission.WRITE_EXTERNAL_STORAGE
                )
                */


        val missingPermissions = getMissingPermissions()


        if (!missingPermissions.isEmpty()) {

            // درخواست مجوزهای لازم از کاربر
            ActivityCompat.requestPermissions(
                activity,
                missingPermissions.toTypedArray(),
                REQUEST_CAMERA_PERMISSION
            )
            Log.e("Camera2", "دسترسی‌های لازم وجود ندارد: ${missingPermissions.joinToString()}")
        }

        if (ContextCompat.checkSelfPermission(
                textureView.context,
                Manifest.permission.CAMERA
            ) == PackageManager.PERMISSION_GRANTED
        ) {
//setup camera called here

            setUpCameraOutputs(width, height)
            configureTransform(width, height)

            cameraManager.openCamera(cameraId, cameraStateCallback, backgroundHandler)


        } else {
            ActivityCompat.requestPermissions(
                activity,
                arrayOf(Manifest.permission.CAMERA),
                REQUEST_CAMERA_PERMISSION
            )
            Log.e("Camera2", "دسترسی وجود ندارد")
        }
    }

    fun getMissingPermissions(): List<String> {
        // تعریف آرایه مجوزها بر اساس نسخه سیستم عامل
        val permissions = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            arrayOf(
                Manifest.permission.CAMERA,
                Manifest.permission.RECORD_AUDIO,
                Manifest.permission.READ_MEDIA_VIDEO
            )
        } else {
            arrayOf(
                Manifest.permission.CAMERA,
                Manifest.permission.RECORD_AUDIO,
                Manifest.permission.READ_EXTERNAL_STORAGE,
                Manifest.permission.WRITE_EXTERNAL_STORAGE
            )
        }
        // بررسی مجوزهایی که هنوز داده نشده‌اند
        return permissions.filter {
            ContextCompat.checkSelfPermission(
                textureView.context,
                it
            ) != PackageManager.PERMISSION_GRANTED
        }
    }


    /**
     * Sets up member variables related to camera.
     *
     * @param width  The width of available size for camera preview
     * @param height The height of available size for camera preview
     */
    private fun setUpCameraOutputs(width: Int, height: Int) {
        try {
            for (cameraId in cameraManager.cameraIdList) {
                val cameraCharacteristics = cameraManager.getCameraCharacteristics(cameraId)
                val cameraFacing = cameraCharacteristics.get(CameraCharacteristics.LENS_FACING)

                if (cameraFacing == this.cameraFacing) {
                    val streamConfigurationMap = cameraCharacteristics.get(
                        CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP
                    )
                    exposureCompensationRange =
                        cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_EXPOSURE_TIME_RANGE)
                    isoRange =
                        cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_SENSITIVITY_RANGE)
                    val minFocusDistance =
                        cameraCharacteristics.get(CameraCharacteristics.LENS_INFO_MINIMUM_FOCUS_DISTANCE)
                            ?: 0f
                    focusRange = Range(0f, minFocusDistance)

                    // مقداردهی به active array و max digital zoom
                    sensorArraySize =
                        cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE)
                    maxDigitalZoom =
                        cameraCharacteristics.get(CameraCharacteristics.SCALER_AVAILABLE_MAX_DIGITAL_ZOOM)
                            ?: 1f


// For still image captures, we use the largest available size.
                    val largest = Collections.max(
                        streamConfigurationMap?.getOutputSizes(ImageFormat.JPEG)?.toList(),
                        compareSizesByArea
                    )
// image reader could go here

// Find out if we need to swap dimension to get the preview size relative to sensor
// coordinate.
                    val displayRotation = activity.windowManager.defaultDisplay.rotation

                    //noinspection ConstantConditions
                    mSensorOrientation =
                        cameraCharacteristics[CameraCharacteristics.SENSOR_ORIENTATION] ?: 0

                    var swappedDimensions = false

                    when (displayRotation) {
                        Surface.ROTATION_0 -> {
                        }

                        Surface.ROTATION_90 -> {
                        }

                        Surface.ROTATION_180 -> {
                            swappedDimensions =
                                mSensorOrientation == 90 || mSensorOrientation == 270
                        }

                        Surface.ROTATION_270 -> {
                            swappedDimensions = mSensorOrientation == 0 || mSensorOrientation == 180
                        }

                        else -> Log.e("Camera2", "Display rotation is invalid: $displayRotation")

                    }

                    val displaySize = Point()

                    activity.windowManager.defaultDisplay.getSize(displaySize)

                    var rotatedPreviewWidth = width
                    var rotatedPreviewHeight = height
                    var maxPreviewWidth = displaySize.x
                    var maxPreviewHeight = displaySize.y

                    if (swappedDimensions) {
                        rotatedPreviewWidth = height
                        rotatedPreviewHeight = width
                        maxPreviewWidth = displaySize.y
                        maxPreviewHeight = displaySize.x
                    }

                    if (maxPreviewWidth > MAX_PREVIEW_WIDTH) {
                        maxPreviewWidth = MAX_PREVIEW_WIDTH
                    }

                    if (maxPreviewHeight > MAX_PREVIEW_HEIGHT) {
                        maxPreviewHeight = MAX_PREVIEW_HEIGHT
                    }


                    // Danger, W.R.! Attempting to use too large a preview size could  exceed the camera
                    // bus' bandwidth limitation, resulting in gorgeous previews but the storage of
                    // garbage capture data.
                    previewSize = chooseOptimalSize(
                        streamConfigurationMap!!.getOutputSizes(SurfaceTexture::class.java),
                        rotatedPreviewWidth, rotatedPreviewHeight, maxPreviewWidth,
                        maxPreviewHeight, largest
                    )

                    // We fit the aspect ratio of TextureView to the size of preview we picked.
                    val orientation = activity.resources.configuration.orientation

                    if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
                        textureView.setAspectRatio(
                            previewSize!!.width, previewSize!!.height
                        )
                    } else {
                        textureView.setAspectRatio(
                            previewSize!!.height, previewSize!!.width
                        )
                    }/*
                    // check flash support
                    val flashSupported = cameraCharacteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE)
                    isFlashSupported = flashSupported == null ?: false*/
                    isFlashSupported =
                        cameraCharacteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE)
                            ?: false
                    this.cameraId = cameraId

                    return
                }
            }
        } catch (e: CameraAccessException) {
            e.printStackTrace()
        }
    }


    /**
     * Configures the necessary [android.graphics.Matrix] transformation to `mTextureView`.
     * This method should be called after the camera preview size is determined in
     * setUpCameraOutputs and also the size of `mTextureView` is fixed.
     *
     * @param viewWidth  The width of `mTextureView`
     * @param viewHeight The height of `mTextureView`
     */
    private fun configureTransform(viewWidth: Int, viewHeight: Int) {
        val rotation = activity.windowManager.defaultDisplay.rotation
        val matrix = Matrix()
        val viewRect = RectF(0f, 0f, viewWidth.toFloat(), viewHeight.toFloat())
        val bufferRect =
            RectF(0f, 0f, previewSize!!.height.toFloat(), previewSize!!.width.toFloat())
        val centerX = viewRect.centerX()
        val centerY = viewRect.centerY()
        if (Surface.ROTATION_90 == rotation || Surface.ROTATION_270 == rotation) {
            bufferRect.offset(centerX - bufferRect.centerX(), centerY - bufferRect.centerY())
            matrix.setRectToRect(viewRect, bufferRect, ScaleToFit.FILL)
            val scale = Math.max(
                viewHeight.toFloat() / previewSize!!.height,
                viewWidth.toFloat() / previewSize!!.width
            )
            matrix.postScale(scale, scale, centerX, centerY)
            matrix.postRotate((90 * (rotation - 2)).toFloat(), centerX, centerY)
        } else if (Surface.ROTATION_180 == rotation) {
            matrix.postRotate(180f, centerX, centerY)
        }
        textureView.setTransform(matrix)
    }

    /**
     * Retrieves the JPEG orientation from the specified screen rotation.
     *
     * @param rotation The screen rotation.
     * @return The JPEG orientation (one of 0, 90, 270, and 360)
     */
    private fun getOrientation(rotation: Int) =

    // Sensor orientation is 90 for most devices, or 270 for some devices (eg. Nexus 5X)
    // We have to take that into account and rotate JPEG properly.
    // For devices with orientation of 90, we simply return our mapping from ORIENTATIONS.
        // For devices with orientation of 270, we need to rotate the JPEG 180 degrees.
        (ORIENTATIONS.get(rotation) + mSensorOrientation + 270) % 360


    private fun openBackgroundThread() {
        backgroundThread = HandlerThread("camera_background_thread")
        backgroundThread!!.start()
        backgroundHandler = Handler(backgroundThread!!.looper)
    }

    // Creates a new camera preview session
    private fun createPreviewSession() {

        try {

            val surfaceTexture = textureView.surfaceTexture
// We configure the size of default buffer to be the size of camera preview we want.
            surfaceTexture?.setDefaultBufferSize(previewSize!!.width, previewSize!!.height)

// This is the output Surface we need to start preview.
            if (surface == null)
                surface = Surface(surfaceTexture)

            val previewSurface = surface
// We set up a CaptureRequest.Builder with the output Surface.

            captureRequestBuilder =
                cameraDevice!!.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW)
            // غیرفعال کردن نوردهی خودکار:
            captureRequestBuilder!!.set(
                CaptureRequest.CONTROL_AE_MODE,
                CameraMetadata.CONTROL_AE_MODE_OFF
            )
            currentExposureTime?.let {
                captureRequestBuilder!!.set(CaptureRequest.SENSOR_EXPOSURE_TIME, it)
            }
            currentIso?.let {
                captureRequestBuilder!!.set(CaptureRequest.SENSOR_SENSITIVITY, it)
            }
            currentFocus?.let {
                captureRequestBuilder!!.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_OFF)
                captureRequestBuilder!!.set(CaptureRequest.LENS_FOCUS_DISTANCE, it)
            }

            captureRequestBuilder!!.addTarget(previewSurface!!)
            /*captureRequestBuilder!!.addTarget(previewSurface!!)*/


// Here, we create a CameraCaptureSession for camera preview.

            cameraDevice!!.createCaptureSession(
                singletonList(previewSurface),
                object : CameraCaptureSession.StateCallback() {

                    override fun onConfigured(cameraCaptureSession: CameraCaptureSession) {
                        if (cameraDevice == null) {
                            return
                        }

                        try {
// When session is ready we start displaying preview.
                            this@Camera2.cameraCaptureSession = cameraCaptureSession
                            //     cameraSessionClosed = false

// Auto focus should be continuous for camera preview.

                            captureRequestBuilder!!.set(
                                CaptureRequest.CONTROL_AF_MODE,
                                CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE
                            )

// Finally, we start displaying the camera preview.
                            captureRequest = captureRequestBuilder!!.build()

                            this@Camera2.cameraCaptureSession!!.setRepeatingRequest(
                                captureRequest!!,
                                cameraCaptureCallBack,
                                backgroundHandler
                            )


                            /* Initially flash is automatically enabled when necessary. But In case activity is resumed and flash is set to fire
                            we set flash after the preview request is processed to ensure flash fires only during a still capture. */
                            setFlashMode(captureRequestBuilder!!, true)

                            cameraReadyCallback?.onCameraReady()

                        } catch (e: CameraAccessException) {
                            e.printStackTrace()
                        }

                    }

                    override fun onConfigureFailed(cameraCaptureSession: CameraCaptureSession) {

                    }
                }, backgroundHandler
            )
        } catch (e: CameraAccessException) {
            e.printStackTrace()
        }

    }

    /* For some reason, The code for firing flash in both methods below which is prescribed doesn't work on API level below PIE it maybe a device-specific issue as very common with Camera API
       so I had to build my own code if the else block works well for your devices even below PIE I would recommend using it because that's
       the official way and code is available for all levels >=21 as mentioned.
    */

    /*    private fun flashOn(captureRequestBuilder: CaptureRequest.Builder) {
            //  cameraManager.setTorchMode()
            if (Build.VERSION.SDK_INT > 28) {
                captureRequestBuilder.set(
                    CaptureRequest.FLASH_MODE,
                    CaptureRequest.FLASH_MODE_TORCH
                )
            } else {
                captureRequestBuilder.set(
                    CaptureRequest.CONTROL_AE_MODE,
                    CaptureRequest.CONTROL_AE_MODE_ON_ALWAYS_FLASH
                )
            }
        }*/

    private fun flashOn(captureRequestBuilder: CaptureRequest.Builder) {
        // برای API level 28 و بالاتر
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            captureRequestBuilder.set(
                CaptureRequest.FLASH_MODE,
                CaptureRequest.FLASH_MODE_TORCH
            )
        } else {
            // برای API level های پایین‌تر
            captureRequestBuilder.set(
                CaptureRequest.CONTROL_AE_MODE,
                CaptureRequest.CONTROL_AE_MODE_ON_ALWAYS_FLASH
            )
            captureRequestBuilder.set(
                CaptureRequest.FLASH_MODE,
                CaptureRequest.FLASH_MODE_TORCH
            )
        }
    }

    // sets flash mode for a capture request builder
    private fun setFlashMode(
        captureRequestBuilder: CaptureRequest.Builder,
        trigger: Boolean
    ) {
        if (trigger) {
            // This is how to tell the camera to trigger.
            captureRequestBuilder.set(
                CaptureRequest.CONTROL_AE_PRECAPTURE_TRIGGER,
                CaptureRequest.CONTROL_AE_PRECAPTURE_TRIGGER_START
            )
        }
        when (flash) {
            FLASH.ON -> flashOn(captureRequestBuilder)
            FLASH.AUTO -> {
                captureRequestBuilder.set(
                    CaptureRequest.CONTROL_AE_MODE,
                    CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH
                )
            }

            else -> captureRequestBuilder.set(
                CaptureRequest.FLASH_MODE,
                CaptureRequest.FLASH_MODE_OFF
            )
        }
    }

    enum class FLASH {
        ON, OFF, AUTO
    }

    // Locks the preview focus.
    private fun lockPreview() {
        try {

            captureRequestBuilder!!.set(
                CaptureRequest.CONTROL_AF_TRIGGER,
                CameraMetadata.CONTROL_AF_TRIGGER_START
            )
// Tell #cameraCaptureCallback to wait for the lock.
            cameraState = STATE_WAITING_LOCK
            cameraCaptureSession!!.capture(
                captureRequestBuilder!!.build(), cameraCaptureCallBack, backgroundHandler
            )
        } catch (e: Exception) {
            e.printStackTrace()
        }

    }


    private fun unlockPreview() {
        try {
// Reset the auto-focus trigger
            captureRequestBuilder!!.set(
                CaptureRequest.CONTROL_AF_TRIGGER,
                CameraMetadata.CONTROL_AF_TRIGGER_CANCEL
            )

            setFlashMode(captureRequestBuilder!!, false)


            cameraCaptureSession!!.capture(
                captureRequestBuilder!!.build(), cameraCaptureCallBack, backgroundHandler
            )
// After this, the camera will go back to the normal state of preview.
            cameraState = STATE_PREVIEW



            cameraCaptureSession!!.setRepeatingRequest(
                captureRequest!!, cameraCaptureCallBack,
                backgroundHandler
            )


        } catch (e: CameraAccessException) {
            e.printStackTrace()
        }

    }

    // This method switches Camera Lens Front or Back then restarts camera.
    fun switchCamera() {
        close()
        cameraFacing = if (cameraFacing == CameraCharacteristics.LENS_FACING_BACK)
            CameraCharacteristics.LENS_FACING_FRONT
        else CameraCharacteristics.LENS_FACING_BACK
        onResume()


    }


    fun setFlash(flash: FLASH) {

        this.flash = flash

        if (textureView.context.packageManager.hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH)) {
            when (cameraFacing) {
//     CameraCharacteristics.LENS_FACING_BACK -> setFlashMode()
                CameraCharacteristics.LENS_FACING_FRONT -> Log.e(
                    "Camera2",
                    "Front Camera Flash isn't supported yet."
                )
            }
        }
    }

    fun getFlash(): FLASH {
        return flash
    }

    // در کلاس Camera2
    fun applyFlashChanges() {
        captureRequestBuilder?.let { builder ->
            setFlashMode(builder, true)
            cameraCaptureSession?.setRepeatingRequest(
                captureRequestBuilder!!.build(),
                cameraCaptureCallBack,
                backgroundHandler
            )
        }
    }

    /**
     * Run the precapture sequence for capturing a still image. This method should be called when
     * we get a response in {@link #mCaptureCallback} from {@link #lockPreview()}.
     */

    private fun runPrecaptureSequence() {
        try {


// Tell #cameraCaptureCallback to wait for the precapture sequence to be set.
            cameraState = STATE_WAITING_PRECAPTURE

            setFlashMode(captureRequestBuilder!!, true)

            cameraCaptureSession!!.capture(
                captureRequestBuilder!!.build(),
                cameraCaptureCallBack,
                backgroundHandler
            )


        } catch (e: CameraAccessException) {
            e.printStackTrace()
        }


    }


    private fun captureBitmap() {
        if (textureView.isAvailable) {
            textureView.bitmap?.let { bitmap ->
                onBitmapReady(bitmap) // Only if the bitmap is not null
            }
        }
    }

    /**
     * Capture a still picture. This method should be called when we get a response in
     * {@link #cameraCaptureCallback} from both {@link #lockPreview()}.
     */
    private fun captureStillPicture() {
        try {
// This is the CaptureRequest.Builder that we use to take a picture.
            val captureBuilder =
                cameraDevice!!.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE)

//            val surfaceTexture = textureView.surfaceTexture
//            surfaceTexture.setDefaultBufferSize(previewSize!!.width, previewSize!!.height)
            captureBuilder.addTarget(surface!!)
            // Use the same AE and AF modes as the preview.
            captureBuilder.set(
                CaptureRequest.CONTROL_AF_MODE,
                CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE
            )


            setFlashMode(captureBuilder, true)

            // Orientation
            val rotation = activity.windowManager.defaultDisplay.rotation

            captureBuilder.set(CaptureRequest.JPEG_ORIENTATION, getOrientation(rotation))

            cameraCaptureSession!!.stopRepeating()
            cameraCaptureSession!!.abortCaptures()
            cameraCaptureSession!!.capture(
                captureBuilder.build(),
                object : CameraCaptureSession.CaptureCallback() {
                    override fun onCaptureCompleted(
                        session: CameraCaptureSession,
                        request: CaptureRequest,
                        result: TotalCaptureResult
                    ) {

                        captureBitmap()
                        unlockPreview()


                    }
                },
                null
            )


        } catch (e: CameraAccessException) {
            e.printStackTrace()
        }
    }


    fun takePhoto(onBitmapReady: (Bitmap) -> Unit) {

        this.onBitmapReady = onBitmapReady
        lockPreview()
    }


    fun setExposureTime(exposureTime: Long, frameRate: Int) {
        // حداکثر زمان نوردهی مجاز بر اساس نرخ فریم (به نانوثانیه)
        val maxExposureTime = (1_000_000_000 / frameRate).toLong() // 1 ثانیه = 1,000,000,000 نانوثانیه
        // محدود کردن exposureTime به حداکثر مجاز
        val adjustedExposureTime = if (exposureTime > maxExposureTime) maxExposureTime else exposureTime
        currentExposureTime = adjustedExposureTime
        captureRequestBuilder?.set(CaptureRequest.SENSOR_EXPOSURE_TIME, adjustedExposureTime)
        captureRequest = captureRequestBuilder?.build()
        try {
            cameraCaptureSession?.setRepeatingRequest(
                captureRequest!!,
                cameraCaptureCallBack,
                backgroundHandler
            )
        } catch (e: CameraAccessException) {
            Log.e("Camera2", "Error setting exposure time: ${e.message}")
        }
        Log.d("Camera2", "Exposure time set to $adjustedExposureTime ns (max: $maxExposureTime ns)")
    }

    fun autoOptimizeExposure() {
        captureRequestBuilder?.let { builder ->
            // استفاده از بازه مجاز زمان نوردهی که در exposureCompensationRange ذخیره شده
            exposureCompensationRange?.let { range ->
                val minExposure = range.lower
                val maxExposure = range.upper
                // محاسبه مقدار میانی (Median)؛ می‌توانید الگوریتم پیشرفته‌تری هم اعمال کنید
                val optimalExposure = (minExposure + maxExposure) / 2
                // تنظیم دستی زمان نوردهی (این مقدار به نانوثانیه است)
                builder.set(CaptureRequest.SENSOR_EXPOSURE_TIME, optimalExposure)
                // به‌روزرسانی درخواست تکراری
                cameraCaptureSession?.setRepeatingRequest(
                    builder.build(),
                    cameraCaptureCallBack,
                    backgroundHandler
                )
            }
        }
    }


    fun setISO(value: Int) {
        currentIso = value
        // غیرفعال کردن نوردهی خودکار برای کنترل دستی ISO
        captureRequestBuilder?.set(
            CaptureRequest.CONTROL_AE_MODE,
            CaptureRequest.CONTROL_AE_MODE_OFF
        )
        // تنظیم دستی ISO
        captureRequestBuilder?.set(CaptureRequest.SENSOR_SENSITIVITY, value)
        captureRequest = captureRequestBuilder?.build()
        cameraCaptureSession?.setRepeatingRequest(
            captureRequest!!,
            cameraCaptureCallBack,
            backgroundHandler
        )
    }

    fun autoOptimizeISO() {
        val defaultISO = 100 // مقدار پیش‌فرض؛ در صورت نیاز می‌توانید این مقدار را تغییر دهید
        setISO(defaultISO)
    }

    fun setManualFocus(focusDistance: Float) {
        currentFocus = focusDistance
        try {
            // توقف درخواست‌های قبلی برای جلوگیری از تداخل
            cameraCaptureSession?.stopRepeating()

            // تنظیم فوکوس دستی
            captureRequestBuilder?.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_OFF)
            captureRequestBuilder?.set(CaptureRequest.LENS_FOCUS_DISTANCE, focusDistance)
            captureRequest = captureRequestBuilder?.build()
            // ارسال درخواست جدید
            cameraCaptureSession?.setRepeatingRequest(
                captureRequest!!,
                cameraCaptureCallBack,
                backgroundHandler
            )
            Log.d("FocusDebug", "Manual Focus Set: $focusDistance")
        } catch (e: CameraAccessException) {
            e.printStackTrace()
            Log.e("FocusDebug", "Error setting manual focus: ${e.message}")
        }
    }

    fun autoOptimizeFocus() {
        // تنظیم فوکوس به حالت بی‌نهایت (معمولاً مقدار 0 در Camera2 API نشان‌دهنده فوکوس بی‌نهایت است)
        setManualFocus(0f)
    }


    // تابع جدید برای تنظیم زوم
    fun setZoom(zoomLevel: Float) {
        // zoomLevel باید بین 1 (بدون زوم) و maxDigitalZoom باشد
        val newZoom = zoomLevel.coerceIn(1f, maxDigitalZoom)
        currentZoom = newZoom  // ذخیره مقدار زوم فعلی
        sensorArraySize?.let { sensorRect ->
            val centerX = sensorRect.centerX()
            val centerY = sensorRect.centerY()
            // محاسبه عرض و ارتفاع جدید crop region بر اساس زوم
            val newWidth = (sensorRect.width() / newZoom).toInt()
            val newHeight = (sensorRect.height() / newZoom).toInt()
            val left = centerX - newWidth / 2
            val top = centerY - newHeight / 2
            val right = left + newWidth
            val bottom = top + newHeight
            val zoomRect = Rect(left, top, right, bottom)
            captureRequestBuilder?.set(CaptureRequest.SCALER_CROP_REGION, zoomRect)
            captureRequest = captureRequestBuilder?.build()
            try {
                cameraCaptureSession?.setRepeatingRequest(
                    captureRequest!!,
                    cameraCaptureCallBack,
                    backgroundHandler
                )
            } catch (e: CameraAccessException) {
                e.printStackTrace()
            }
        }
    }


    /**
     * تابع برای پیکربندی MediaRecorder
     * پارامتر outputFile مسیر فایل خروجی ضبط شده است.
     */

    private fun setUpMediaRecorder(context: Context, outputFile: String, framerate: Int) {
        mediaRecorder = MediaRecorder()
        mediaRecorder?.apply {
            // تنظیم منابع صوتی و تصویری
            setAudioSource(MediaRecorder.AudioSource.MIC)
            setVideoSource(MediaRecorder.VideoSource.SURFACE)

            Log.d("Camera2", "Video will be saved at: $outputFile")

            // تنظیم فرمت خروجی
            setOutputFormat(MediaRecorder.OutputFormat.MPEG_4)


            // در اندروید 13 و بالاتر، از MediaStore استفاده کنید
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                val values = ContentValues().apply {
                    // نام فایل خروجی به صورت منحصر به فرد
                    put(
                        MediaStore.Video.Media.DISPLAY_NAME,
                        "video_${System.currentTimeMillis()}.mp4"
                    )
                    put(MediaStore.Video.Media.MIME_TYPE, "video/mp4")
                    // ذخیره در پوشه عمومی Movies (یا Videos)
                    put(
                        MediaStore.Video.Media.RELATIVE_PATH,
                        Environment.DIRECTORY_MOVIES + "/DistributedCameras"
                    )
                }
                val resolver = context.contentResolver
                val videoUri = resolver.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, values)
                if (videoUri != null) {
                    val fd = resolver.openFileDescriptor(videoUri, "w")?.fileDescriptor
                    if (fd != null) {
                        setOutputFile(fd)
                    } else {
                        Log.e("Camera2", "Failed to obtain FileDescriptor for videoUri")
                    }
                } else {
                    Log.e("Camera2", "Failed to insert video into MediaStore")
                }
            } else {
                // برای نسخه‌های پایین‌تر از اندروید 13، مسیر فایل خروجی مستقیم مورد استفاده قرار می‌گیرد
                try {
                    // **اینجا مسیر فایل خروجی را تنظیم کنید**
                    setOutputFile(outputFile)
                    Log.d("Camera2", "MediaRecorder setup successful")
                } catch (e: Exception) {
                    Log.e("Camera2", "Error in MediaRecorder setup: ${e.message}")
                }
            }

            // تنظیمات کدگذاری ویدئو – می‌توانید این مقادیر را تغییر دهید
            setVideoEncodingBitRate(10000000)
            setVideoFrameRate(framerate)
            // اندازه ویدئو را بر اساس previewSize انتخاب می‌کنیم
            previewSize?.let {
                setVideoSize(it.width, it.height)
            } ?: run {
                // در صورت نبود اندازه مناسب، از یک مقدار پیش‌فرض استفاده کنید
                setVideoSize(1920, 1080)
            }
            setVideoEncoder(MediaRecorder.VideoEncoder.H264)
            setAudioEncoder(MediaRecorder.AudioEncoder.AAC)

            // تنظیم جهت چرخش ویدئو بر اساس جهت سنسور
            val rotation = activity.windowManager.defaultDisplay.rotation
            val orientation = getOrientation(rotation)
            setOrientationHint(orientation)

            prepare()
        }
    }


    /**
     * پیش‌پیکربندی session ضبط ویدئو با استفاده از یک capture session مشترک برای پیش‌نمایش و ضبط.
     * این متد باید قبل از شروع ضبط (و بعد از آنکه کاربر آماده ضبط شود) فراخوانی شود.
     */
    fun prepareVideoRecordingSession(
        context: Context,
        outputFile: String,
        currentExposureValue: Long,
        currentIsoValue: Int,
        currentFocusValue: Float,
        framerate: Int,
        autostart: Boolean = false
    ) {
        // محاسبه یک‌باره در شروع ضبط
        val currentTimeMillis = System.currentTimeMillis()
        val elapsedRealtimeNanos = SystemClock.elapsedRealtimeNanos()
        bootTimeMillis = currentTimeMillis - (elapsedRealtimeNanos / 1_000_000)

        if (cameraDevice == null || !textureView.isAvailable || previewSize == null) return

        cameraCaptureSession?.close()
        cameraCaptureSession = null
        videoTimestamps.clear()

        // پیکربندی MediaRecorder
        setUpMediaRecorder(context, outputFile, framerate)
        timestampFilePath = outputFile // ذخیره موقت مسیر فایل ویدئو

        // تنظیم اندازه بافر سطح TextureView
        val texture = textureView.surfaceTexture
        texture?.setDefaultBufferSize(previewSize!!.width, previewSize!!.height)
        val previewSurface = Surface(texture)
        val recorderSurface = mediaRecorder!!.surface

        // ایجاد CaptureRequest برای حالت ضبط (TEMPLATE_RECORD)
        captureRequestBuilder =
            cameraDevice!!.createCaptureRequest(CameraDevice.TEMPLATE_RECORD).apply {
                set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_OFF)
                set(CaptureRequest.SENSOR_EXPOSURE_TIME, currentExposureValue)
                set(CaptureRequest.SENSOR_SENSITIVITY, currentIsoValue)
                set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_OFF)
                set(CaptureRequest.LENS_FOCUS_DISTANCE, currentFocusValue)
                addTarget(previewSurface)
                addTarget(recorderSurface)

                // اعمال زوم فعلی به CaptureRequest
                if (currentZoom > 1f) {
                    sensorArraySize?.let { sensorRect ->
                        val centerX = sensorRect.centerX()
                        val centerY = sensorRect.centerY()
                        val newWidth = (sensorRect.width() / currentZoom).toInt()
                        val newHeight = (sensorRect.height() / currentZoom).toInt()
                        val left = centerX - newWidth / 2
                        val top = centerY - newHeight / 2
                        val right = left + newWidth
                        val bottom = top + newHeight
                        val zoomRect = Rect(left, top, right, bottom)
                        set(CaptureRequest.SCALER_CROP_REGION, zoomRect)
                    }
                }
            }


        // ایجاد یک capture session مشترک شامل هر دو سطح
        cameraDevice!!.createCaptureSession(
            listOf(previewSurface, recorderSurface),
            object : CameraCaptureSession.StateCallback() {
                override fun onConfigured(session: CameraCaptureSession) {
                    cameraCaptureSession = session
                    captureRequest = captureRequestBuilder!!.build()
                    // شروع به ارسال درخواست‌های تکراری
                    cameraCaptureSession!!.setRepeatingRequest(
                        captureRequest!!,
                        timestampCollectingCallback,
                        backgroundHandler
                    )
                    Log.d("Camera2", "Shared capture session for preview and recording configured")
                }

                override fun onConfigureFailed(session: CameraCaptureSession) {
                    Log.e("Camera2", "Configuration failed when preparing video session")
                }
            },
            backgroundHandler
        )

        if (autostart)
            startRecordingVideo()
    }

    /**
     * شروع ضبط ویدئو با استفاده از session از پیش پیکربندی‌شده.
     * در اینجا نیازی به ایجاد session جدید نیست؛ فقط ضبط توسط MediaRecorder آغاز می‌شود.
     */
    fun startRecordingVideo() {
        try {
            // شروع ضبط به صورت فوری
            mediaRecorder?.start()
            isRecordingVideo = true
            Log.d("Camera2", "Video recording started with zero reconfiguration delay")
        } catch (e: Exception) {
            e.printStackTrace()
            Log.e("Camera2", "Error while starting video recording: ${e.message}")
        }
    }


    /**
     * توقف ضبط ویدئو.
     * پس از توقف، یک session جدید preview ایجاد می‌شود.
     */
    fun stopRecordingVideo() {
        if (!isRecordingVideo) {
            Log.e("Camera2", "MediaRecorder stop called while not recording!")
            return
        } else {
            try {
                isRecordingVideo = false
                // توقف ضبط
                mediaRecorder?.apply {
                    try {
                        stop()
                        reset()
                        release()
                    } catch (e: Exception) {
                        // در صورت خطا (مثلاً اگر ضبط به درستی آغاز نشده باشد)
                        e.printStackTrace()
                        Log.e(
                            "Camera2",
                            "MediaRecorder stop called while not recording! : ${e.message}"
                        )
                    }
                }
                mediaRecorder = null
                // ذخیره timestampها بعد از توقف
                timestampFilePath?.let { saveTimestampsToFile(activity, it) } // activity به عنوان context
                cameraCaptureSession?.close()
                cameraCaptureSession = null
            } catch (e: Exception) {
                Log.e("Camera2", "خطا در توقف ضبط: ${e.message}")
                e.printStackTrace()
            }
        }
        // بازگرداندن preview
        createPreviewSession()

    }




    fun collectTimestampsWithoutStopping(numFrames: Int = 50, callback: (List<Long>) -> Unit) {
        val timestamps = mutableListOf<Long>()
        val captureCallback = object : CameraCaptureSession.CaptureCallback() {
            override fun onCaptureCompleted(
                session: CameraCaptureSession,
                request: CaptureRequest,
                result: TotalCaptureResult
            ) {
                val timestamp = result.get(CaptureResult.SENSOR_TIMESTAMP) ?: return
                timestamps.add(timestamp)
                if (timestamps.size == numFrames) { // دقیقاً وقتی به numFrames رسید
                    callback(timestamps) // فراخوانی callback با لیست timestampها
                    // برگرداندن درخواست تکراری به حالت اصلی
                    try {
                        session.setRepeatingRequest(
                            captureRequest!!, // درخواست اصلی پیش‌نمایش
                            cameraCaptureCallBack, // callback اصلی پیش‌نمایش
                            backgroundHandler
                        )
                    } catch (e: CameraAccessException) {
                        Log.e("Camera2", "Error resetting repeating request: ${e.message}")
                    }
                }
            }
        }

        try {
            cameraCaptureSession?.setRepeatingRequest(
                captureRequestBuilder!!.build(),
                captureCallback,
                backgroundHandler
            )
        } catch (e: CameraAccessException) {
            Log.e("Camera2", "Error collecting timestamps: ${e.message}")
        }
    }

    // Callback جدید برای جمع‌آوری timestampها در حین ضبط ویدئو
// Wrapper برای cameraCaptureCallBack که timestampها رو هم جمع‌آوری می‌کنه
    private val timestampCollectingCallback = object : CameraCaptureSession.CaptureCallback() {
        override fun onCaptureCompleted(
            session: CameraCaptureSession,
            request: CaptureRequest,
            result: TotalCaptureResult
        ) {
            // اجرای منطق اصلی cameraCaptureCallBack
            cameraCaptureCallBack.onCaptureCompleted(session, request, result)

            // جمع‌آوری timestamp بدون تغییر در رفتار اصلی
            //val timestamp = result.get(CaptureResult.SENSOR_TIMESTAMP) ?: return
            //videoTimestamps.add(timestamp)

            // جمع‌آوری timestamp و تبدیل به زمان Unix
            val sensorTimestamp = result.get(CaptureResult.SENSOR_TIMESTAMP) ?: return
            val unixTimestamp = convertToUnixTime(sensorTimestamp)
            videoTimestamps.add(unixTimestamp)
        }

        override fun onCaptureProgressed(
            session: CameraCaptureSession,
            request: CaptureRequest,
            partialResult: CaptureResult
        ) {
            // اجرای منطق اصلی cameraCaptureCallBack
            cameraCaptureCallBack.onCaptureProgressed(session, request, partialResult)
        }
    }

    // متد ذخیره timestampها در فایل
    private fun saveTimestampsToFile(context: Context, videoFileName: String) {
        // چک می‌کنیم که آیا timestamp داریم یا نه
        if (videoTimestamps.isEmpty()) {
            Log.e("Camera2", "هیچ timestampی جمع‌آوری نشده!")
            return
        }

// استخراج فقط نام فایل ویدئو بدون مسیر
        val videoFileName = File(videoFileName).name

        // ساخت نام فایل timestamp بر اساس نام ویدئو
        val timestampFileName = videoFileName.replace(".mp4", "_timestamps.txt")

        // ذخیره با MediaStore برای همه نسخه‌ها
        val values = ContentValues().apply {
            put(MediaStore.Files.FileColumns.DISPLAY_NAME, timestampFileName)
            put(MediaStore.Files.FileColumns.MIME_TYPE, "text/plain")
            put(MediaStore.Files.FileColumns.RELATIVE_PATH, Environment.DIRECTORY_DOCUMENTS + "/DistributedCameras")
        }

        val resolver = context.contentResolver
        val uri = resolver.insert(MediaStore.Files.getContentUri("external"), values)
        uri?.let {
            resolver.openOutputStream(it)?.use { outputStream ->
                outputStream.write(videoTimestamps.joinToString("\n").toByteArray())
            }
            Log.d("Camera2", "فایل timestamp در $uri ذخیره شد")
            // نمایش پیام به کاربر
            (context as? Activity)?.runOnUiThread {
                Toast.makeText(context, "Timestamps have been saved in DCIM/DistributedCameras", Toast.LENGTH_SHORT).show();
            }
        } ?: run {
            Log.e("Camera2", "خطا در ایجاد فایل timestamp")
        }
    }

    private fun convertToUnixTime(sensorTimestamp: Long): Long {
        if (role == "slave")
        {
            val unixTimeMillis = bootTimeMillis + (sensorTimestamp / 1_000_000) // زمان Unix محلی
            val offset = TimeSyncManager.getOffset() // افست محاسبه‌شده
            return unixTimeMillis + offset // زمان هماهنگ‌شده با مستر
        }
        else{
            // استفاده از مقدار ذخیره‌شده
            val unixTimeMillis = bootTimeMillis + (sensorTimestamp / 1_000_000)
            return unixTimeMillis
        }
    }



    fun setCameraReadyCallback(callback: CameraReadyCallback) {
        this.cameraReadyCallback = callback
    }


    interface CameraReadyCallback {
        fun onCameraReady()
    }
}